// Reasoning tokens generated by dragging chart elements
export interface ReasoningToken {
  id: string;
  type: 'baseline' | 'delta';
  channel: string;
  channelName: string;
  metric: 'spend' | 'clicks' | 'revenue' | 'profit';
  value: number;
  // Delta-specific fields
  direction?: 'increase' | 'decrease';
  deltaValue?: number;
  baselineValue?: number;
  currentValue?: number;
  // Timestamp for tracking
  createdAt: number;
}

export function createBaselineToken(
  channel: string,
  channelName: string,
  metric: 'spend' | 'clicks' | 'revenue' | 'profit',
  value: number
): ReasoningToken {
  return {
    id: `baseline-${channel}-${metric}-${Date.now()}`,
    type: 'baseline',
    channel,
    channelName,
    metric,
    value,
    createdAt: Date.now(),
  };
}

export function createDeltaToken(
  channel: string,
  channelName: string,
  metric: 'spend' | 'clicks' | 'revenue' | 'profit',
  baselineValue: number,
  currentValue: number
): ReasoningToken {
  const deltaValue = currentValue - baselineValue;
  return {
    id: `delta-${channel}-${metric}-${Date.now()}`,
    type: 'delta',
    channel,
    channelName,
    metric,
    value: Math.abs(deltaValue),
    direction: deltaValue > 0 ? 'increase' : 'decrease',
    deltaValue,
    baselineValue,
    currentValue,
    createdAt: Date.now(),
  };
}
